### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by beutlich** [fmi-crosscheck/ESi#1]
Please fix the repository name to ESI-ITI.

**Comment by xogeny** [comment]
Sorry, I wasn't clear.  I wanted it in the `fmi-crosscheck-tools` repository which is the central issue tracker for all crosscheck toolings related issues.  I've added there:

https://github.com/modelica/fmi-crosscheck-tools/issues/9

...so I'm closing this one.

**Comment by beutlich** [comment]
The rep description still reads: FMI Cross-Check data for ESi

**Comment by xogeny** [comment]
Fixed.  But note that this is something that you can do yourself.  It doesn't impact the crosscheck stuff at all.  In any case, it is done now.  But in the future vendors are responsible for maintaining their individual repositories (e.g., collaborators, README, milestones, etc).  We just read the repo.  So the only thing we (the MA) care about is the the URL for the repository (which is why I had to make some changes on the fmi-crosscheck-tools side).
